# Running IPCA + RFF geometric analysis of complexity for 500 stocks and 30 years data

## Loading data

In [1]:
#imports

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import missingno as msno
import itertools

import numpy as np
from matplotlib import pyplot as plt

import autograd.numpy as anp
from pymanopt import Problem
from pymanopt.manifolds import Grassmann
from pymanopt.function import autograd as pymanopt_autograd
from pymanopt.optimizers import ConjugateGradient, SteepestDescent, TrustRegions

import requests
import zipfile
import io
import os
import sys
from pathlib import Path

ROOT_DIR = Path.cwd().parent
for p in [ROOT_DIR, ROOT_DIR / "src"]:
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

from src.rff import RandomFourierFeatures

In [2]:
# load data from ipca_char_data_filtered.parquet

DATA_DIR = ROOT_DIR / "data"
df_char_filtered = pd.read_parquet(DATA_DIR / "ipca_char_data_filtered.parquet")

In [3]:
df_char_filtered.head()

,permno,yyyymm,AM,AbnormalAccruals,AnnouncementReturn,AssetGrowth,BMdec,Beta,BetaFP,BetaLiquidityPS,...,VolumeTrend,betaVIX,cfp,dNoa,hire,Price,Size,STreversal,excess_ret,y_ipca
6359,10104,1994-01-01,0.127079,0.116246,-0.118802,-0.239069,0.133073,1.985119,2.026764,-0.295296,...,-0.011868,0.021741,0.034075,0.108471,-0.124892,-3.469635,-9.139615,-0.117391,0.117391,0.027237
6360,10104,1994-02-01,0.125607,0.116246,-0.118802,-0.239069,0.133073,1.972944,2.008414,-0.284722,...,-0.011071,-0.000676,0.033680,0.108471,-0.124892,-3.496508,-9.151264,-0.027237,0.027237,-0.026515
6361,10104,1994-03-01,0.129029,0.116246,0.005112,-0.239069,0.133073,1.951014,2.014694,-0.301786,...,-0.010681,-0.012093,0.034598,0.108471,-0.124892,-3.469635,-9.124391,0.026515,-0.026515,-0.070039
6362,10104,1994-04-01,0.138746,0.116246,0.005112,-0.239069,0.133073,1.946702,2.041135,-0.179182,...,-0.010495,-0.001282,0.037203,0.108471,-0.124892,-3.397022,-9.051779,0.070039,-0.070039,0.146444
6363,10104,1994-05-01,0.120721,0.116246,0.005112,-0.239069,0.133073,1.935432,2.041004,-0.186885,...,-0.010062,0.011399,0.032370,0.108471,-0.124892,-3.533687,-9.190940,-0.146444,0.146444,0.094891

In [4]:
# check if any column has nan/missin values
df_char_filtered.isna().sum()
# only print the columns with missing values
print(df_char_filtered.isna().sum()[df_char_filtered.isna().sum() > 0])
#check if these columns with missing values are important for our analysis, if not we can drop them
missing_columns = df_char_filtered.isna().sum()[df_char_filtered.isna().sum() > 0].index
#print(df_char_filtered[missing_columns].head())
#print the dates in whch these columns have missing values
#print(df_char_filtered[df_char_filtered[missing_columns].isna().any(axis=1)].yyyymm.unique())
# find the longest consecutive sequence of missing values in these columns(streak in terms of date)
for col in missing_columns:
    is_missing = df_char_filtered[col].isna()
    max_streak = 0
    current_streak = 0
    for missing in is_missing:
        if missing:
            current_streak += 1
            max_streak = max(max_streak, current_streak)
        else:
            current_streak = 0
    print(f"Column: {col}, Max Consecutive Missing Values: {max_streak}")
#show the number of missing values per permno
missing_by_permno = df_char_filtered.groupby("permno")[missing_columns].apply(lambda x: x.isna().sum())
#show in the order of decreasing number of missing values
missing_by_permno = missing_by_permno.sort_values(by=missing_columns.tolist(), ascending=False)
print(missing_by_permno.head(20))

excess_ret    403
y_ipca        476
dtype: int64
Column: excess_ret, Max Consecutive Missing Values: 85
Column: y_ipca, Max Consecutive Missing Values: 85
        excess_ret  y_ipca
permno
81593           85      86
10693           44      44
21020           24      25
11896           14      14
84723            5       5
90090            3       3
81061            2       2
81138            2       2
81857            2       2
82298            2       2
82486            2       2
82618            2       2
82643            2       2
82686            2       2
82759            2       2
83111            2       2
83435            2       2
83906            2       2
84597            2       2
84761            2       2

In [5]:
#Lets drop the top4 and fill the others with previous values
permnos_to_drop = missing_by_permno.head(4).index
df_char_filtered = df_char_filtered[~df_char_filtered.permno.isin(permnos_to_drop)]
df_char_filtered[missing_columns] = df_char_filtered[missing_columns].fillna(method="ffill")

/var/folders/js/pgf30x597b53rt2mghx7jpmm0000gn/T/ipykernel_5496/3808254857.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_char_filtered[missing_columns] = df_char_filtered[missing_columns].fillna(method="ffill")

In [6]:
#Now lets check if there are any missing values left
print(df_char_filtered.isna().sum()[df_char_filtered.isna().sum() > 0])

Series([], dtype: int64)

In [7]:
#print the number of columns
print(f"Number of columns: {df_char_filtered.shape[1]}")

Number of columns: 78

## Import parallel sweep helpers from src._grass_worker

In [11]:
import sys
import importlib
from pathlib import Path
import types

from src._grass_worker import (
    build_rff_inputs, build_jobs, run_sweep, aggregate, make_results_df,
    Z_VALUES, _z_label,
    GAMMA, WINDOW_LEN, N_FEATURES_RFF, NUM_FACTORS_LIST, NUM_ITER_RFF,
)
# Ensure src/ is on sys.path so top-level modules in src can be imported
src_dir = ROOT_DIR / "src" #this seems to be the only way to reliably import from src/ in both .ipynb and .py contexts without causing import errors in one or the other
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

# Try to import the real module; if missing, install a lightweight shim to avoid ImportError
try:
    backtest_GRASS_IPCA = importlib.import_module("backtest_GRASS_IPCA")
except Exception:
    shim = types.ModuleType("backtest_GRASS_IPCA")
    def run_backtest(*args, **kwargs):
        raise RuntimeError("backtest_GRASS_IPCA.run_backtest is not available in this environment.")
    shim.run_backtest = run_backtest
    # add any other expected symbols here as simple stubs if you discover they're required
    sys.modules["backtest_GRASS_IPCA"] = shim
    backtest_GRASS_IPCA = shim
    print("Warning: using shim for backtest_GRASS_IPCA (real module not found).")

## Prepare panel: MultiIndex (date, permno), lag characteristics, rename target

In [12]:
# Convert yyyymm → datetime, set MultiIndex (date, permno)
df = df_char_filtered.copy()
df["date"] = pd.to_datetime(df["yyyymm"])
df = df.drop(columns=["yyyymm"]).set_index(["date", "permno"]).sort_index()

# Characteristic columns (all except the return target)
char_cols = [c for c in df.columns if c != "y_ipca"]
print(f"Characteristic columns ({len(char_cols)}): {char_cols[:6]} ...")

# # Lag characteristics 1 period within each permno (Z_{t-1} predicts r_t)
# df[char_cols] = df[char_cols].groupby(level="permno").shift(1)

# Rename return column to the convention expected by run_ipca_grass_v2
df = df.rename(columns={"y_ipca": "ret"})
df = df.dropna(subset=["ret"])

# build_rff_inputs expects df_base to have a "Price" column alongside "ret";
# it is not used by the backtest — add a dummy so the API stays unchanged.
df["Price"] = 1.0

print(f"Panel shape   : {df.shape}")
print(f"Date range    : {df.index.get_level_values('date').min().date()} → "
      f"{df.index.get_level_values('date').max().date()}")
print(f"Unique permnos: {df.index.get_level_values('permno').nunique()}")

Characteristic columns (75): ['AM', 'AbnormalAccruals', 'AnnouncementReturn', 'AssetGrowth', 'BMdec', 'Beta'] ...
Panel shape   : (170070, 76)
Date range    : 1994-01-01 → 2024-12-01
Unique permnos: 496

## RFF expansion of characteristics

In [15]:
# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
N_FEATURES_RFF   = [256, 1024, 4096]   # low/mid/high — captures P-scaling cleanly
NUM_FACTORS_LIST = [4, 8, 16, 32]      # brackets the expected k₀ for 500 stocks
NUM_ITER_RFF     = 3                   # keep at 3, enough to average out RFF noise
WINDOW_LEN       = 12                  # keep as is
GAMMA            = 0.25                # keep as is
Z_VALUES         = [0, 10, 100]        # zero (illusory baseline), sweet spot, over-regularised       # 0.0 = OLS baseline; add e.g. 1e-2, 1.0 for shrinkage

# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (170070, 75)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [16]:
X_chars

                         AM  AbnormalAccruals  AnnouncementReturn  \
date       permno
1994-01-01 10104   0.127079          0.116246           -0.118802
           10107   0.157391         -0.033059            0.016113
           10138   0.217930          0.063340           -0.008250
           10145   0.965586         -0.031255            0.014178
           10147   0.084075         -0.029539           -0.087328
...                     ...               ...                 ...
2024-12-01 91068   0.097906         -0.011654           -0.002130
           91152   0.280245         -0.126017           -0.002130
           91233   0.088510         -0.071839           -0.002130
           91556   0.286242         -0.025738           -0.002130
           92655   0.587969          0.002143           -0.002130

                   AssetGrowth     BMdec      Beta    BetaFP  BetaLiquidityPS  \
date       permno
1994-01-01 10104     -0.239069  0.133073  1.985119  2.026764        -0.295296
           10107     -0.441341  0.136106  0.693257  2.018450        -0.292866
           10138     -0.147580  0.235116  1.174992  1.626780        -0.535108
           10145     -0.036024  0.310770  0.690762  1.345882        -0.096328
           10147     -0.689566  0.178950  0.841710  1.862470         1.242027
...                        ...       ...       ...       ...              ...
2024-12-01 91068     -0.161221  0.050208  0.903377  1.370571        -0.099407
           91152     -0.102888 -0.024251  1.156308  1.185805         0.034896
           91233     -0.096168  0.018390  0.751810  0.905866        -0.103534
           91556     -0.065863  0.108767  0.806443  1.031322        -0.101743
           92655     -0.114019  0.188475  0.366384  1.086882        -0.034096

                   BidAskSpread  BookLeverage  ...       VolSD  VolumeTrend  \
date       permno                              ...
1994-01-01 10104       0.010590     -2.207913  ...  -12.208052    -0.011868
           10107       0.004754     -1.173658  ...  -10.796080    -0.023260
           10138       0.012367     -1.336412  ...   -0.613418    -0.027808
           10145       0.002165     -4.039054  ...   -2.297178    -0.002215
           10147       0.009352     -1.968820  ...   -6.550222    -0.053044
...                         ...           ...  ...         ...          ...
2024-12-01 91068       0.003504     -2.552699  ... -112.505424     0.000863
           91152       0.005843     14.716286  ...   -1.367359     0.017825
           91233       0.005106     -5.816388  ...  -15.292991     0.014815
           91556       0.004045     -2.821890  ...  -15.863852     0.002186
           92655       0.006129     -2.982447  ...  -19.846913     0.000043

                    betaVIX       cfp      dNoa      hire  Price       Size  \
date       permno
1994-01-01 10104   0.021741  0.034075  0.108471 -0.124892    1.0  -9.139615
           10107   0.009281  0.044425 -0.036221 -0.222393    1.0 -10.093095
           10138  -0.013582  0.047705 -0.076672 -0.093941    1.0  -6.851806
           10145  -0.005273  0.095966  0.202947  0.095949    1.0  -9.318240
           10147   0.021300  0.005905 -0.261023 -0.231917    1.0  -8.246562
...                     ...       ...       ...       ...    ...        ...
2024-12-01 91068   0.000104  0.021706 -0.089222 -0.100531    1.0 -11.316477
           91152   0.000067  0.019296 -0.069089 -0.073579    1.0 -11.174079
           91233   0.001235  0.024980 -0.028200 -0.110585    1.0 -13.080672
           91556   0.001618  0.050332 -0.022481 -0.066986    1.0 -10.818940
           92655   0.001036  0.062440 -0.056092 -0.095238    1.0 -13.050942

                   STreversal  excess_ret
date       permno
1994-01-01 10104    -0.117391    0.117391
           10107    -0.055814    0.055814
           10138    -0.120690    0.120690
           10145     0.004747   -0.004747
           10147    -0.250000    0.250000
...                       ...         ...
2024-12-01 91068     0.019831   -0.019831
           91152    -0.011421    0.011421
           91233     0.011953   -0.011953
           91556     0.020872   -0.020872
           92655     0.167552   -0.167552

[170070 rows x 75 columns]

## Rolling IPCA + RFF parallel sweep

Mirrors the cell-40 pattern from `VOC_everywhere.ipynb`:
1. `build_rff_inputs` — pre-compute all (n_feat × seed) RFF DataFrames
2. `build_jobs` — build full (k, P, z, seed) Cartesian job list, sorted longest-first (LPT)
3. `run_sweep` — dispatch in parallel via joblib/loky
4. `aggregate` + `make_results_df` — average over seeds → MultiIndex summary

### Run with 496 stocks, kernel is crashing

In [11]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  9 RFF datasets ready.

:

### Results — plots

In [ ]:
fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle(
    f"IPCA + RFF on 500 stocks (1994-2025)\n"
    f"window_len={WINDOW_LEN} months, gamma={GAMMA}, z={Z_VALUES}",
    fontsize=13,
)

metrics = [
    ("avg_r2_oos",               "OOS R²"),
    ("avg_sharpe",               "Sharpe (annualised)"),
    ("avg_subspace_stability",   "Mean d_proj  (↓ better)"),
    ("avg_erank",                "Mean erank(Σ̂_f)  (↑ better)"),
    ("avg_spectral_gap",         "Spectral gap ratio  (↑ better)"),
    ("avg_max_principal_angle",  "Max principal angle rad  (↓ better)"),
]

for ax, (col, title) in zip(axes.flat, metrics):
    for nf in NUM_FACTORS_LIST:
        subset = results_rff_df.xs(nf, level="k")[col]
        ax.plot(subset.index.get_level_values("P"), subset.values,
                marker="o", label=f"k={nf}")
    ax.set_title(title)
    ax.set_xlabel("N_FEATURES_RFF  (P)")
    ax.set_xscale("log")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.4)

plt.tight_layout()
plt.show()

### Run with top50 stocks

### Loading top50(mkt cap) stocks

In [13]:
import wrds
import pandas as pd

db = wrds.Connection()

# Get the 496 permnos already in your panel
panel_permnos = df_char_filtered["permno"].unique().tolist()
permnos_str = ",".join(map(str, panel_permnos))

sql = f"""
    SELECT
        msf.permno,
        msf.date,
        ABS(msf.prc) * msf.shrout AS me
    FROM crsp.msf
    JOIN crsp.msenames AS names
      ON msf.permno = names.permno
     AND msf.date BETWEEN names.namedt AND names.nameendt
    WHERE msf.date    >= '1994-01-01'
      AND msf.date    <= '2025-12-31'
      AND msf.permno  IN ({permnos_str})
"""
df_me = db.raw_sql(sql, date_cols=["date"])
db.close()

top50_permnos = (
    df_me.groupby("permno")["me"]
    .mean()
    .nlargest(50)
    .index.tolist()
)

df_top50 = df_char_filtered[df_char_filtered["permno"].isin(top50_permnos)]
print(f"Stocks: {len(top50_permnos)}, Panel shape: {df_top50.shape}")

WRDS recommends setting up a .pgpass file.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done
Stocks: 50, Panel shape: (17803, 78)

In [14]:
import wrds

db = wrds.Connection()

permnos_str = ",".join(map(str, top50_permnos))

name_map = db.raw_sql(f"""
    SELECT DISTINCT ON (permno) permno, ticker, comnam
    FROM crsp.msenames
    WHERE permno IN ({permnos_str})
    ORDER BY permno, namedt DESC   -- most recent name entry
""")

print(name_map.sort_values("comnam").to_string(index=False))

WRDS recommends setting up a .pgpass file.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done
 permno ticker                           comnam
  22592    MMM                            3M CO
  66093      T                      A T & T INC
  20482    ABT              ABBOTT LABORATORIES
  90319  GOOGL                     ALPHABET INC
  13901     MO                 ALTRIA GROUP INC
  84788   AMZN                   AMAZON COM INC
  59176    AXP              AMERICAN EXPRESS CO
  66800    AIG AMERICAN INTERNATIONAL GROUP INC
  14008   AMGN                        AMGEN INC
  14593   AAPL                        APPLE INC
  59408    BAC             BANK OF AMERICA CORP
  83443    BRK       BERKSHIRE HATHAWAY INC DEL
  17778    BRK       BERKSHIRE HATHAWAY INC DEL
  19561     BA                        BOEING CO
  19393    BMY          BRISTOL MYERS SQUIBB CO
  14541    CVX                 CHEVRON CORP NEW
  76076   CSCO                CISCO SYSTEMS INC
  70519      C                    CITIGROUP INC
  11308     KO                     COCA COLA CO
  89525  CMCSA                 COMCAST CORP NEW
  87055   COST        COSTCO WHOLESALE CORP NEW
  26403    DIS                   DISNEY WALT CO
  11850    XOM                 EXXON MOBIL CORP
  12060     GE              GENERAL ELECTRIC CO
  86868     GS          GOLDMAN SACHS GROUP INC
  66181     HD                   HOME DEPOT INC
  59328   INTC                       INTEL CORP
  12490    IBM INTERNATIONAL BUSINESS MACHS COR
  22111    JNJ                JOHNSON & JOHNSON
  47896    JPM              JPMORGAN CHASE & CO
  50876    LLY                   LILLY ELI & CO
  91233     MA                   MASTERCARD INC
  43449    MCD                   MCDONALDS CORP
  60097    MDT                    MEDTRONIC PLC
  22752    MRK               MERCK & CO INC NEW
  10107   MSFT                   MICROSOFT CORP
  69032     MS  MORGAN STANLEY DEAN WITTER & CO
  89393   NFLX                      NETFLIX INC
  86580   NVDA                      NVIDIA CORP
  10104   ORCL                      ORACLE CORP
  13856    PEP                      PEPSICO INC
  21936    PFE                       PFIZER INC
  18163     PG              PROCTER & GAMBLE CO
  77178   QCOM                     QUALCOMM INC
  17830    RTX                       R T X CORP
  90215    CRM                   SALESFORCE INC
  92655    UNH           UNITEDHEALTH GROUP INC
  65875     VZ       VERIZON COMMUNICATIONS INC
  55976    WMT                      WALMART INC
  38703    WFC             WELLS FARGO & CO NEW

In [15]:
name_map

    permno ticker                            comnam
0    10104   ORCL                       ORACLE CORP
1    10107   MSFT                    MICROSOFT CORP
2    11308     KO                      COCA COLA CO
3    11850    XOM                  EXXON MOBIL CORP
4    12060     GE               GENERAL ELECTRIC CO
5    12490    IBM  INTERNATIONAL BUSINESS MACHS COR
6    13856    PEP                       PEPSICO INC
7    13901     MO                  ALTRIA GROUP INC
8    14008   AMGN                         AMGEN INC
9    14541    CVX                  CHEVRON CORP NEW
10   14593   AAPL                         APPLE INC
11   17778    BRK        BERKSHIRE HATHAWAY INC DEL
12   17830    RTX                        R T X CORP
13   18163     PG               PROCTER & GAMBLE CO
14   19393    BMY           BRISTOL MYERS SQUIBB CO
15   19561     BA                         BOEING CO
16   20482    ABT               ABBOTT LABORATORIES
17   21936    PFE                        PFIZER INC
18   22111    JNJ                 JOHNSON & JOHNSON
19   22592    MMM                             3M CO
20   22752    MRK                MERCK & CO INC NEW
21   26403    DIS                    DISNEY WALT CO
22   38703    WFC              WELLS FARGO & CO NEW
23   43449    MCD                    MCDONALDS CORP
24   47896    JPM               JPMORGAN CHASE & CO
25   50876    LLY                    LILLY ELI & CO
26   55976    WMT                       WALMART INC
27   59176    AXP               AMERICAN EXPRESS CO
28   59328   INTC                        INTEL CORP
29   59408    BAC              BANK OF AMERICA CORP
30   60097    MDT                     MEDTRONIC PLC
31   65875     VZ        VERIZON COMMUNICATIONS INC
32   66093      T                       A T & T INC
33   66181     HD                    HOME DEPOT INC
34   66800    AIG  AMERICAN INTERNATIONAL GROUP INC
35   69032     MS   MORGAN STANLEY DEAN WITTER & CO
36   70519      C                     CITIGROUP INC
37   76076   CSCO                 CISCO SYSTEMS INC
38   77178   QCOM                      QUALCOMM INC
39   83443    BRK        BERKSHIRE HATHAWAY INC DEL
40   84788   AMZN                    AMAZON COM INC
41   86580   NVDA                       NVIDIA CORP
42   86868     GS           GOLDMAN SACHS GROUP INC
43   87055   COST         COSTCO WHOLESALE CORP NEW
44   89393   NFLX                       NETFLIX INC
45   89525  CMCSA                  COMCAST CORP NEW
46   90215    CRM                    SALESFORCE INC
47   90319  GOOGL                      ALPHABET INC
48   91233     MA                    MASTERCARD INC
49   92655    UNH            UNITEDHEALTH GROUP INC

In [16]:
#lets see if there are any missing nans in df_top50
print(df_top50.isna().sum()[df_top50.isna().sum() > 0])

Series([], dtype: int64)

### Simulate with top50 stocks

In [17]:
# prepare panel like above for the top50 stocks and run the backtest on this smaller universe to see if we can get better convergence with more RFF features and more iterations
df = df_top50.copy()
df["date"] = pd.to_datetime(df["yyyymm"])
df = df.drop(columns=["yyyymm"]).set_index(["date", "permno"]).sort_index()

# Characteristic columns (all except the return target)
char_cols = [c for c in df.columns if c not in ("y_ipca", "excess_ret")]
print(f"Characteristic columns ({len(char_cols)}): {char_cols[:6]} ...")

# # Lag characteristics 1 period within each permno (Z_{t-1} predicts r_t)
# df[char_cols] = df[char_cols].groupby(level="permno").shift(1)

# Rename return column to the convention expected by run_ipca_grass_v2
df = df.rename(columns={"y_ipca": "ret"})
df = df.dropna(subset=["ret"])

# build_rff_inputs expects df_base to have a "Price" column alongside "ret";
# it is not used by the backtest — add a dummy so the API stays unchanged.
df["Price"] = 1.0

print(f"Panel shape   : {df.shape}")
print(f"Date range    : {df.index.get_level_values('date').min().date()} → "
      f"{df.index.get_level_values('date').max().date()}")
print(f"Unique permnos: {df.index.get_level_values('permno').nunique()}")

Characteristic columns (74): ['AM', 'AbnormalAccruals', 'AnnouncementReturn', 'AssetGrowth', 'BMdec', 'Beta'] ...
Panel shape   : (17803, 76)
Date range    : 1994-01-01 → 2024-12-01
Unique permnos: 50

### Run1 : k = {1, 4, 8, 12, 16, 24}, z: {0,10}

In [35]:
# these will have one nan per columns, as we shifted to make Z_t-1) predict r_t, so this is expected

In [ ]:
# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
NUM_FACTORS_LIST = [4, 8, 12, 16, 24]     # below k₀, at k₀, above k₀
Z_VALUES         = [0, 10]         # illusory baseline vs virtuous
N_FEATURES_RFF   = [1024]          # P-independence already established
NUM_ITER_RFF     = 3
WINDOW_LEN       = 12
GAMMA            = 0.25
# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [21]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  3 RFF datasets ready.
Dispatching 30 jobs across 7 workers (cost range 8192–120397, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.925381e-03
  OOS R²                               : -0.0921
  Market-timing Sharpe (annualised)    : -0.047

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.2626  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.1818  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0177  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0653  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.2114  (max = 16)
  erank collapse fraction              : 0.8750  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.0468  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.6088  (max = 5.6569)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 9.236728e-03
  OOS R²                               : -0.1302
  Market-timing Sharpe (annualised)    : -0.146

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.1664  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.1160  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0069  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0457  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.8728  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.0243  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 6.8457  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 9.224221e-03
  OOS R²                               : -0.1287
  Market-timing Sharpe (annualised)    : 0.279

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.1697  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.1182  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0071  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0455  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.9229  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.0248  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 6.8459  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   3 out of  30 | elapsed: 10.0min remaining: 90.3min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 9.285695e-03
  OOS R²                               : -0.1362
  Market-timing Sharpe (annualised)    : 0.504

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.1635  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.1136  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0069  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0477  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.7198  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.0239  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 6.8456  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.880100e-03
  OOS R²                               : -0.0866
  Market-timing Sharpe (annualised)    : -0.068

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.2642  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.1825  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0179  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0656  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.1747  (max = 16)
  erank collapse fraction              : 0.8056  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.0471  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.6082  (max = 5.6569)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.866605e-03
  OOS R²                               : -0.0849
  Market-timing Sharpe (annualised)    : -0.045

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.2695  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.1867  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0181  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0703  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.3492  (max = 16)
  erank collapse fraction              : 0.8472  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.0480  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.6081  (max = 5.6569)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.767633e-03
  OOS R²                               : -0.0728
  Market-timing Sharpe (annualised)    : 0.123

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.3490  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.2414  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0323  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0877  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 6.6500  (max = 12)
  erank collapse fraction              : 0.1833  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0014  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.0717  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.8606  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   7 out of  30 | elapsed: 40.0min remaining: 131.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.753437e-03
  OOS R²                               : -0.0711
  Market-timing Sharpe (annualised)    : -0.149

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.3467  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.2397  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0322  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0979  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 6.5275  (max = 12)
  erank collapse fraction              : 0.2333  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0013  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.0712  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.8600  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.755390e-03
  OOS R²                               : -0.0713
  Market-timing Sharpe (annualised)    : 0.035

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.3383  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.2338  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0313  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0896  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 6.5979  (max = 12)
  erank collapse fraction              : 0.1889  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0013  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.0695  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.8603  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.424933e-03
  OOS R²                               : -0.0309
  Market-timing Sharpe (annualised)    : 0.047

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3259  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1222  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0778  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0957  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8282  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.1938  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.2911  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.401783e-03
  OOS R²                               : -0.0280
  Market-timing Sharpe (annualised)    : 0.358

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3209  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1172  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0774  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0982  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8335  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.1930  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.2916  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  11 out of  30 | elapsed: 94.2min remaining: 162.8min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.407741e-03
  OOS R²                               : -0.0288
  Market-timing Sharpe (annualised)    : 0.302

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3207  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1183  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0774  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0990  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8258  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.1930  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.2936  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.400792e-03
  OOS R²                               : -0.0279
  Market-timing Sharpe (annualised)    : 0.361

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3459  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0993  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1267  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1162  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8041  (max = 16)
  erank collapse fraction              : 0.0389  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.2399  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.6576  (max = 5.6569)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.428052e-03
  OOS R²                               : -0.0313
  Market-timing Sharpe (annualised)    : 0.018

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3487  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0990  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1277  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1227  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.7974  (max = 16)
  erank collapse fraction              : 0.0417  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.2404  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.6554  (max = 5.6569)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.408538e-03
  OOS R²                               : -0.0289
  Market-timing Sharpe (annualised)    : 0.288

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3494  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1064  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1267  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1066  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.7960  (max = 16)
  erank collapse fraction              : 0.0389  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.2405  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.6533  (max = 5.6569)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  15 out of  30 | elapsed: 102.8min remaining: 102.8min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.661984e-03
  OOS R²                               : -0.0599
  Market-timing Sharpe (annualised)    : 0.196

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.4540  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.3119  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0648  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1132  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 5.6256  (max = 8)
  erank collapse fraction              : 0.0222  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0431  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.1140  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.9545  (max = 4.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.640639e-03
  OOS R²                               : -0.0573
  Market-timing Sharpe (annualised)    : 0.042

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.4507  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.3105  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0638  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1142  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 5.6080  (max = 8)
  erank collapse fraction              : 0.0056  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0435  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.1132  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.9550  (max = 4.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.621775e-03
  OOS R²                               : -0.0550
  Market-timing Sharpe (annualised)    : 0.374

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.4585  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.3164  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0652  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1269  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ���───────────────────
  Mean erank                           : 5.5082  (max = 8)
  erank collapse fraction              : 0.0278  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0392  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.1151  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.9528  (max = 4.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.763151e-03
  OOS R²                               : -0.0723
  Market-timing Sharpe (annualised)    : 0.198

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.5870  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.3962  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1623  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1355  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.4196  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2273  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.2080  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.7462  (max = 2.8284)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  19 out of  30 | elapsed: 126.0min remaining: 73.0min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.403982e-03
  OOS R²                               : -0.0283
  Market-timing Sharpe (annualised)    : 0.354

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3859  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0371  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1917  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1200  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.5375  (max = 12)
  erank collapse fraction              : 0.0194  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0456  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.2847  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.6547  (max = 4.8990)
  Flat-Hessian fraction                : 0.7528  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.709960e-03
  OOS R²                               : -0.0657
  Market-timing Sharpe (annualised)    : -0.070

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.5938  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.4000  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1642  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.1455  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.3464  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2070  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.2104  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.7460  (max = 2.8284)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.730077e-03
  OOS R²                               : -0.0682
  Market-timing Sharpe (annualised)    : -0.028

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.5854  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.3943  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1614  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.1421  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.3816  (max = 4)
  erank collapse fraction              : 0.0083  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2285  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.2075  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.7451  (max = 2.8284)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.427632e-03
  OOS R²                               : -0.0312
  Market-timing Sharpe (annualised)    : 0.030

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3950  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0456  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1938  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1413  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.5287  (max = 12)
  erank collapse fraction              : 0.0167  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0464  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.2866  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.6584  (max = 4.8990)
  Flat-Hessian fraction                : 0.7917  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  23 out of  30 | elapsed: 169.0min remaining: 51.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.410098e-03
  OOS R²                               : -0.0291
  Market-timing Sharpe (annualised)    : 0.307

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3881  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0509  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1905  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1320  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.5420  (max = 12)
  erank collapse fraction              : 0.0167  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0476  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.2852  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.6491  (max = 4.8990)
  Flat-Hessian fraction                : 0.7667  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.423810e-03
  OOS R²                               : -0.0307
  Market-timing Sharpe (annualised)    : 0.300

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3974  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9313  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2815  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1045  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 7.4072  (max = 8)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.3037  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.3509  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.2847  (max = 4.0000)
  Flat-Hessian fraction                : 0.9083  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.460606e-03
  OOS R²                               : -0.0352
  Market-timing Sharpe (annualised)    : -0.126

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4039  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9302  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2838  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.1252  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.4014  (max = 8)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.3028  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.3525  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.2970  (max = 4.0000)
  Flat-Hessian fraction                : 0.9222  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.428673e-03
  OOS R²                               : -0.0313
  Market-timing Sharpe (annualised)    : 0.200

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3981  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9340  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2808  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1148  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ���───────────────────
  Mean erank                           : 7.4321  (max = 8)
  erank collapse fraction              : 0.0028  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.3144  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.3511  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.2952  (max = 4.0000)
  Flat-Hessian fraction                : 0.9333  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  27 out of  30 | elapsed: 176.4min remaining: 19.6min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.489148e-03
  OOS R²                               : -0.0387
  Market-timing Sharpe (annualised)    : 0.289

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.2378  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8094  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.4013  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1172  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.8946  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.5688  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.4387  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.1185  (max = 2.8284)
  Flat-Hessian fraction                : 0.9917  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.505204e-03
  OOS R²                               : -0.0407
  Market-timing Sharpe (annualised)    : -0.006

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.2372  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.7947  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.4007  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1118  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.8899  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.5655  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.4385  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.1089  (max = 2.8284)
  Flat-Hessian fraction                : 0.9944  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.502330e-03
  OOS R²                               : -0.0403
  Market-timing Sharpe (annualised)    : 0.090

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.2384  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8041  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.4014  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1138  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 3.9057  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.5886  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.4389  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.1005  (max = 2.8284)
  Flat-Hessian fraction                : 0.9806  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  30 out of  30 | elapsed: 196.8min finished

                 avg_r2_oos  avg_sharpe  avg_subspace_stability  \
k  P    z
4  1024 z=0e+00   -0.068738    0.033662                0.588709
        z=1e+01   -0.039922    0.124149                1.237812
8  1024 z=0e+00   -0.057367    0.204040                0.454414
        z=1e+01   -0.032434    0.124780                1.399760
12 1024 z=0e+00   -0.071727    0.003268                0.344688
        z=1e+01   -0.029523    0.230358                1.389662
16 1024 z=0e+00   -0.087863   -0.053282                0.265426
        z=1e+01   -0.029346    0.222280                1.348005
24 1024 z=0e+00   -0.131690    0.212184                0.166530
        z=1e+01   -0.029227    0.235614                1.322483

                 avg_max_principal_angle  avg_mean_principal_angle  \
k  P    z
4  1024 z=0e+00                 0.396841                  0.162658
        z=1e+01                 0.802710                  0.401132
8  1024 z=0e+00                 0.312912                  0.064608
        z=1e+01                 0.931821                  0.282069
12 1024 z=0e+00                 0.238305                  0.031907
        z=1e+01                 1.044526                  0.191994
16 1024 z=0e+00                 0.183657                  0.017896
        z=1e+01                 1.101556                  0.127026
24 1024 z=0e+00                 0.115938                  0.006965
        z=1e+01                 1.119238                  0.077522

                 avg_geodesic_accel  avg_erank  avg_erank_collapse  \
k  P    z
4  1024 z=0e+00            0.141023   3.382539            0.002778
        z=1e+01            0.114294   3.896735            0.000000
8  1024 z=0e+00            0.118081   5.580585            0.018519
        z=1e+01            0.114831   7.413556            0.000926
12 1024 z=0e+00            0.091721   6.591813            0.201852
        z=1e+01            0.131073   9.536090            0.017593
16 1024 z=0e+00            0.067055   7.245099            0.842593
        z=1e+01            0.115175   9.799155            0.039815
24 1024 z=0e+00            0.046309   7.838482            1.000000
        z=1e+01            0.097656   9.829161            1.000000

                 avg_spectral_gap
k  P    z
4  1024 z=0e+00      2.209187e-01
        z=1e+01      5.742925e-01
8  1024 z=0e+00      4.193812e-02
        z=1e+01      3.069561e-01
12 1024 z=0e+00      1.341996e-03
        z=1e+01      4.654315e-02
16 1024 z=0e+00      9.301977e-20
        z=1e+01      2.700167e-19
24 1024 z=0e+00      0.000000e+00
        z=1e+01      0.000000e+00

### Run2  z = {1, 5, 25, 100} atk=12, T = 24

In [29]:
# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
NUM_FACTORS_LIST = [12]     # below k₀, at k₀, above k₀
Z_VALUES         = [1, 5, 25, 100]         # illusory baseline vs virtuous
N_FEATURES_RFF   = [1024]          # P-independence already established
NUM_ITER_RFF     = 3
WINDOW_LEN       = 24
GAMMA            = 0.25
# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [30]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  3 RFF datasets ready.
Dispatching 12 jobs across 7 workers (cost range 42567–42567, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.517403e-03
  OOS R²                               : -0.0251
  Market-timing Sharpe (annualised)    : 0.258

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.7015  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.4766  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0876  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0934  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 10.1779  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.1296  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.1441  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.4384  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   1 out of  12 | elapsed: 93.3min remaining: 1026.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.530603e-03
  OOS R²                               : -0.0267
  Market-timing Sharpe (annualised)    : -0.064

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.7042  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.4776  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0883  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0898  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 10.1657  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.1266  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.1447  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ────────────────────��
  Mean d_proj (warm vs random init)    : 4.4432  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.518970e-03
  OOS R²                               : -0.0253
  Market-timing Sharpe (annualised)    : 0.191

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.7010  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.4765  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0875  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0800  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 10.2268  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.1217  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.1440  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.4399  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   3 out of  12 | elapsed: 93.8min remaining: 281.5min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.514376e-03
  OOS R²                               : -0.0247
  Market-timing Sharpe (annualised)    : 0.208

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.0902  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.6982  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1611  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1187  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.2888  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.3163  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.2240  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.5139  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.505397e-03
  OOS R²                               : -0.0237
  Market-timing Sharpe (annualised)    : 0.316

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5220  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9319  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2391  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1312  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.4670  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4091  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3127  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.3888  (max = 4.8990)
  Flat-Hessian fraction                : 0.4224  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   5 out of  12 | elapsed: 97.4min remaining: 136.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.515985e-03
  OOS R²                               : -0.0249
  Market-timing Sharpe (annualised)    : 0.207

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.0935  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.6974  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1629  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1215  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.2530  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.3082  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.2246  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 3.5184  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.525852e-03
  OOS R²                               : -0.0261
  Market-timing Sharpe (annualised)    : -0.006

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.0908  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.6961  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1622  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.1191  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.2421  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2987  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.2241  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ────────────────────��
  Mean d_proj (warm vs random init)    : 3.5199  (max = 4.8990)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   7 out of  12 | elapsed: 97.7min remaining: 69.8min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.497478e-03
  OOS R²                               : -0.0227
  Market-timing Sharpe (annualised)    : 0.360

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.6788  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0764  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2707  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1978  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.4485  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4144  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3449  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 1.4792  (max = 4.8990)
  Flat-Hessian fraction                : 0.0029  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.512099e-03
  OOS R²                               : -0.0245
  Market-timing Sharpe (annualised)    : 0.218

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5188  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9265  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2389  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1340  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.4935  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4224  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3120  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.3669  (max = 4.8990)
  Flat-Hessian fraction                : 0.3621  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   9 out of  12 | elapsed: 211.6min remaining: 70.5min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.513024e-03
  OOS R²                               : -0.0246
  Market-timing Sharpe (annualised)    : 0.097

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5285  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9198  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2411  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1234  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 11.4695  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4081  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3140  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.3806  (max = 4.8990)
  Flat-Hessian fraction                : 0.4253  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.500334e-03
  OOS R²                               : -0.0230
  Market-timing Sharpe (annualised)    : 0.329

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.6718  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0767  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2697  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1760  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 11.4703  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4271  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3434  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 1.4707  (max = 4.8990)
  Flat-Hessian fraction                : 0.0029  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.514637e-03
  OOS R²                               : -0.0248
  Market-timing Sharpe (annualised)    : -0.005

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.6895  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0807  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2741  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1728  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ���───────────────────
  Mean erank                           : 11.4429  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4089  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3471  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 1.5328  (max = 4.8990)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  12 out of  12 | elapsed: 213.3min finished

                 avg_r2_oos  avg_sharpe  avg_subspace_stability  \
k  P    z
12 1024 z=1e+00   -0.025695    0.128234                0.702229
        z=1e+02   -0.023507    0.228131                1.680029
        z=2e+01   -0.024232    0.210213                1.523093
        z=5e+00   -0.025263    0.136353                1.091539

                 avg_max_principal_angle  avg_mean_principal_angle  \
k  P    z
12 1024 z=1e+00                 0.476902                  0.087819
        z=1e+02                 1.077929                  0.271522
        z=2e+01                 0.926063                  0.239712
        z=5e+00                 0.697246                  0.162069

                 avg_geodesic_accel  avg_erank  avg_erank_collapse  \
k  P    z
12 1024 z=1e+00            0.087755  10.190136                 0.0
        z=1e+02            0.182214  11.453914                 0.0
        z=2e+01            0.129528  11.476672                 0.0
        z=5e+00            0.119769  11.261268                 0.0

                 avg_spectral_gap
k  P    z
12 1024 z=1e+00          0.125995
        z=1e+02          0.416803
        z=2e+01          0.413193
        z=5e+00          0.307757

In [31]:
results_rff_df

                 avg_r2_oos  avg_sharpe  avg_subspace_stability  \
k  P    z
12 1024 z=1e+00   -0.025695    0.128234                0.702229
        z=1e+02   -0.023507    0.228131                1.680029
        z=2e+01   -0.024232    0.210213                1.523093
        z=5e+00   -0.025263    0.136353                1.091539

                 avg_max_principal_angle  avg_mean_principal_angle  \
k  P    z
12 1024 z=1e+00                 0.476902                  0.087819
        z=1e+02                 1.077929                  0.271522
        z=2e+01                 0.926063                  0.239712
        z=5e+00                 0.697246                  0.162069

                 avg_geodesic_accel  avg_erank  avg_erank_collapse  \
k  P    z
12 1024 z=1e+00            0.087755  10.190136                 0.0
        z=1e+02            0.182214  11.453914                 0.0
        z=2e+01            0.129528  11.476672                 0.0
        z=5e+00            0.119769  11.261268                 0.0

                 avg_spectral_gap
k  P    z
12 1024 z=1e+00          0.125995
        z=1e+02          0.416803
        z=2e+01          0.413193
        z=5e+00          0.307757

### Run3 : NUM_FACTORS_LIST = [4, 8, 12, 16, 24], Z_VALUES         = [20]

In [32]:
# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
NUM_FACTORS_LIST = [4, 8, 12, 16, 24]     # below k₀, at k₀, above k₀
Z_VALUES         = [20]         # illusory baseline vs virtuous
N_FEATURES_RFF   = [1024]          # P-independence already established
NUM_ITER_RFF     = 3
WINDOW_LEN       = 24
GAMMA            = 0.25
# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [33]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  3 RFF datasets ready.
Dispatching 15 jobs across 7 workers (cost range 8192–120397, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.505127e-03
  OOS R²                               : -0.0236
  Market-timing Sharpe (annualised)    : 0.275

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4884  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.9073  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2320  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1264  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.4646  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4064  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3058  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5396  (max = 4.8990)
  Flat-Hessian fraction                : 0.6523  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.511116e-03
  OOS R²                               : -0.0243
  Market-timing Sharpe (annualised)    : 0.099

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5937  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0280  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1949  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1313  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 14.7478  (max = 16)
  erank collapse fraction              : 0.0029  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2857  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.2841  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.6231  (max = 5.6569)
  Flat-Hessian fraction                : 0.1322  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   2 out of  15 | elapsed: 170.6min remaining: 1108.9min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.501042e-03
  OOS R²                               : -0.0231
  Market-timing Sharpe (annualised)    : 0.316

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5964  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0337  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1945  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1195  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 14.7750  (max = 16)
  erank collapse fraction              : 0.0057  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2940  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.2846  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5869  (max = 5.6569)
  Flat-Hessian fraction                : 0.0862  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.495046e-03
  OOS R²                               : -0.0224
  Market-timing Sharpe (annualised)    : 0.394

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5951  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.0367  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1947  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1230  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 14.7604  (max = 16)
  erank collapse fraction              : 0.0057  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.2903  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.6097  (expected d_proj for 2 Haar-random pts on Gr(1024,16))
  Mean d_proj_norm                     : 0.2843  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5922  (max = 5.6569)
  Flat-Hessian fraction                : 0.1092  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   4 out of  15 | elapsed: 172.0min remaining: 473.0min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.493875e-03
  OOS R²                               : -0.0223
  Market-timing Sharpe (annualised)    : 0.361

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5324  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1984  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1162  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1425  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.6467  (max = 24)
  erank collapse fraction              : 0.0345  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0402  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.2239  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.4996  (max = 6.9282)
  Flat-Hessian fraction                : 0.0603  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.490744e-03
  OOS R²                               : -0.0219
  Market-timing Sharpe (annualised)    : 0.408

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5387  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2011  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1176  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1368  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.6710  (max = 24)
  erank collapse fraction              : 0.0345  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0392  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.2249  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5000  (max = 6.9282)
  Flat-Hessian fraction                : 0.0603  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   6 out of  15 | elapsed: 191.3min remaining: 287.0min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.504556e-03
  OOS R²                               : -0.0236
  Market-timing Sharpe (annualised)    : 0.082

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5349  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2059  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1165  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1428  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.6521  (max = 24)
  erank collapse fraction              : 0.0374  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0373  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.2243  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.4898  (max = 6.9282)
  Flat-Hessian fraction                : 0.0632  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.525073e-03
  OOS R²                               : -0.0260
  Market-timing Sharpe (annualised)    : 0.144

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3627  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.7776  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2941  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1351  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 7.7940  (max = 8)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.5242  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.3422  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.4246  (max = 4.0000)
  Flat-Hessian fraction                : 0.9655  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   8 out of  15 | elapsed: 322.9min remaining: 282.5min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.530098e-03
  OOS R²                               : -0.0266
  Market-timing Sharpe (annualised)    : 0.049

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3654  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.7735  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2959  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1242  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 7.8045  (max = 8)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.5292  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.3429  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.4450  (max = 4.0000)
  Flat-Hessian fraction                : 0.9569  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.513122e-03
  OOS R²                               : -0.0246
  Market-timing Sharpe (annualised)    : 0.094

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4958  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8942  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2342  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1204  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 11.4684  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4065  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3073  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5458  (max = 4.8990)
  Flat-Hessian fraction                : 0.6667  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  10 out of  15 | elapsed: 333.4min remaining: 166.7min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.510937e-03
  OOS R²                               : -0.0243
  Market-timing Sharpe (annualised)    : 0.230

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4853  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8988  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2313  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1296  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 11.4914  (max = 12)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.4193  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 4.8678  (expected d_proj for 2 Haar-random pts on Gr(1024,12))
  Mean d_proj_norm                     : 0.3051  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5080  (max = 4.8990)
  Flat-Hessian fraction                : 0.6149  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.541691e-03
  OOS R²                               : -0.0280
  Market-timing Sharpe (annualised)    : 0.265

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.2067  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.6687  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.4193  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1936  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 3.9474  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.6781  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.4277  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.3117  (max = 2.8284)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  12 out of  15 | elapsed: 337.6min remaining: 84.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.570134e-03
  OOS R²                               : -0.0314
  Market-timing Sharpe (annualised)    : -0.070

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.2049  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.6618  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.4186  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.1908  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.9448  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.6653  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.4270  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.2760  (max = 2.8284)
  Flat-Hessian fraction                : 0.9971  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.511601e-03
  OOS R²                               : -0.0244
  Market-timing Sharpe (annualised)    : 0.227

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3683  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.7765  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.2961  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1393  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 7.8153  (max = 8)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.5382  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 3.9824  (expected d_proj for 2 Haar-random pts on Gr(1024,8))
  Mean d_proj_norm                     : 0.3436  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.4362  (max = 4.0000)
  Flat-Hessian fraction                : 0.9655  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.528210e-03
  OOS R²                               : -0.0264
  Market-timing Sharpe (annualised)    : 0.421

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.2122  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.6653  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.4223  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.2016  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 3.9573  (max = 4)
  erank collapse fraction              : 0.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.7039  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 2.8215  (expected d_proj for 2 Haar-random pts on Gr(1024,4))
  Mean d_proj_norm                     : 0.4296  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.3150  (max = 2.8284)
  Flat-Hessian fraction                : 0.9971  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  15 out of  15 | elapsed: 364.3min finished

,,,avg_r2_oos,avg_sharpe,avg_subspace_stability,avg_max_principal_angle,avg_mean_principal_angle,avg_geodesic_accel,avg_erank,avg_erank_collapse,avg_spectral_gap
k,P,z,,,,,,,,,
4,1024,z=2e+01,-0.028626,0.205029,1.207916,0.665261,0.420080,0.195350,3.949825,0.000000,0.682406
8,1024,z=2e+01,-0.025686,0.139891,1.365448,0.775875,0.295348,0.132879,7.804608,0.000000,0.530543
12,1024,z=2e+01,-0.024179,0.199393,1.489824,0.900135,0.232489,0.125496,11.474806,0.000000,0.410738
16,1024,z=2e+01,-0.023297,0.269948,1.595065,1.032811,0.194694,0.124586,14.761079,0.004789,0.289968
24,1024,z=2e+01,-0.022573,0.283874,1.535360,1.201785,0.116767,0.140719,18.656600,0.035441,0.038902

### Run4 : n_rff : N_FEATURES_RFF   = [16, 64,256,1024, 4096]

In [38]:
# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
NUM_FACTORS_LIST = [24]     # below k₀, at k₀, above k₀
Z_VALUES         = [20]         # illusory baseline vs virtuous
N_FEATURES_RFF   = [64,256,1024, 4096]         
NUM_ITER_RFF     = 3
WINDOW_LEN       = 24
GAMMA            = 0.25
# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [39]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  12 RFF datasets ready.
Dispatching 12 jobs across 7 workers (cost range 7525–481589, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.522815e-03
  OOS R²                               : -0.0258
  Market-timing Sharpe (annualised)    : 0.334

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4317  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4893  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0798  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0283  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.1100  (max = 24)
  erank collapse fraction              : 0.0431  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0653  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.5826  (expected d_proj for 2 Haar-random pts on Gr(256,24))
  Mean d_proj_norm                     : 0.2175  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 0.2924  (max = 6.9282)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   1 out of  12 | elapsed: 84.5min remaining: 929.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.492708e-03
  OOS R²                               : -0.0221
  Market-timing Sharpe (annualised)    : 0.389

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5323  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1967  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1163  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1460  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.6451  (max = 24)
  erank collapse fraction              : 0.0345  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0412  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.2239  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5084  (max = 6.9282)
  Flat-Hessian fraction                : 0.0632  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.491112e-03
  OOS R²                               : -0.0219
  Market-timing Sharpe (annualised)    : 0.407

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5362  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1996  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1173  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1454  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.6694  (max = 24)
  erank collapse fraction              : 0.0374  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0386  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.2245  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5055  (max = 6.9282)
  Flat-Hessian fraction                : 0.0603  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   3 out of  12 | elapsed: 145.0min remaining: 435.1min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.504846e-03
  OOS R²                               : -0.0236
  Market-timing Sharpe (annualised)    : 0.081

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.5331  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2074  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.1166  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.1490  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.6502  (max = 24)
  erank collapse fraction              : 0.0374  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0366  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.8432  (expected d_proj for 2 Haar-random pts on Gr(1024,24))
  Mean d_proj_norm                     : 0.2240  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 2.5094  (max = 6.9282)
  Flat-Hessian fraction                : 0.0690  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.530921e-03
  OOS R²                               : -0.0267
  Market-timing Sharpe (annualised)    : 0.195

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4308  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4901  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0800  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0255  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 18.1468  (max = 24)
  erank collapse fraction              : 0.0517  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0664  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.5826  (expected d_proj for 2 Haar-random pts on Gr(256,24))
  Mean d_proj_norm                     : 0.2174  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 0.2962  (max = 6.9282)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   5 out of  12 | elapsed: 247.0min remaining: 345.9min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.597246e-03
  OOS R²                               : -0.0347
  Market-timing Sharpe (annualised)    : 0.065

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4209  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4384  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0837  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0314  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 16.2241  (max = 24)
  erank collapse fraction              : 0.0690  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0273  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.4349  (expected d_proj for 2 Haar-random pts on Gr(64,24))
  Mean d_proj_norm                     : 0.2614  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 0.0233  (max = 6.9282)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.604102e-03
  OOS R²                               : -0.0355
  Market-timing Sharpe (annualised)    : -0.000

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4192  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4339  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0836  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0403  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 16.2937  (max = 24)
  erank collapse fraction              : 0.0690  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0285  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.4349  (expected d_proj for 2 Haar-random pts on Gr(64,24))
  Mean d_proj_norm                     : 0.2611  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 0.0307  (max = 6.9282)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   7 out of  12 | elapsed: 257.8min remaining: 184.1min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.597392e-03
  OOS R²                               : -0.0347
  Market-timing Sharpe (annualised)    : 0.024

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4199  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4429  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0834  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0293  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 16.1791  (max = 24)
  erank collapse fraction              : 0.0690  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0281  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 5.4349  (expected d_proj for 2 Haar-random pts on Gr(64,24))
  Mean d_proj_norm                     : 0.2612  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 0.0180  (max = 6.9282)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.510043e-03
  OOS R²                               : -0.0242
  Market-timing Sharpe (annualised)    : 0.439

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4316  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4906  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0797  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0281  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 18.2616  (max = 24)
  erank collapse fraction              : 0.0402  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0669  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.5826  (expected d_proj for 2 Haar-random pts on Gr(256,24))
  Mean d_proj_norm                     : 0.2175  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 0.2730  (max = 6.9282)
  Flat-Hessian fraction                : 0.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   9 out of  12 | elapsed: 294.2min remaining: 98.1min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.481737e-03
  OOS R²                               : -0.0208
  Market-timing Sharpe (annualised)    : 0.416

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.1666  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8657  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0872  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1200  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ���───────────────────
  Mean erank                           : 17.8052  (max = 24)
  erank collapse fraction              : 0.0287  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0032  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.1689  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.0497  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.479478e-03
  OOS R²                               : -0.0205
  Market-timing Sharpe (annualised)    : 0.543

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.1673  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8635  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0876  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1343  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 17.7928  (max = 24)
  erank collapse fraction              : 0.0287  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0032  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.1690  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.0674  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.489694e-03
  OOS R²                               : -0.0218
  Market-timing Sharpe (annualised)    : 0.319

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.1729  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.8674  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0878  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.1389  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 17.8319  (max = 24)
  erank collapse fraction              : 0.0287  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0030  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.1698  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.0243  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  12 out of  12 | elapsed: 348.8min finished

                 avg_r2_oos  avg_sharpe  avg_subspace_stability  \
k  P    z
24 64   z=2e+01   -0.034993    0.029264                1.419981
   256  z=2e+01   -0.025566    0.322742                1.431380
   1024 z=2e+01   -0.022553    0.292026                1.533880
   4096 z=2e+01   -0.021038    0.425746                1.168918

                 avg_max_principal_angle  avg_mean_principal_angle  \
k  P    z
24 64   z=2e+01                 1.438387                  0.083558
   256  z=2e+01                 1.489980                  0.079834
   1024 z=2e+01                 1.201230                  0.116747
   4096 z=2e+01                 0.865519                  0.087508

                 avg_geodesic_accel  avg_erank  avg_erank_collapse  \
k  P    z
24 64   z=2e+01            0.033678  16.232313            0.068966
   256  z=2e+01            0.027295  18.172800            0.045019
   1024 z=2e+01            0.146800  18.654884            0.036398
   4096 z=2e+01            0.131056  17.809959            0.028736

                 avg_spectral_gap
k  P    z
24 64   z=2e+01          0.027958
   256  z=2e+01          0.066218
   1024 z=2e+01          0.038813
   4096 z=2e+01          0.003130

### k sweep = [28, 32, 36], z_values = [0, 10]

In [16]:
# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
NUM_FACTORS_LIST = [28, 32]     # below k₀, at k₀, above k₀
Z_VALUES         = [0, 10]         # illusory baseline vs virtuous
N_FEATURES_RFF   = [1024]          # P-independence already established
NUM_ITER_RFF     = 3
WINDOW_LEN       = 12
GAMMA            = 0.25
# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [17]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  3 RFF datasets ready.
Dispatching 12 jobs across 7 workers (cost range 151718–185364, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 9.572000e-03
  OOS R²                               : -0.1712
  Market-timing Sharpe (annualised)    : 0.197

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.1248  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.0871  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0043  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0384  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 8.0027  (max = 28)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.3767  (expected d_proj for 2 Haar-random pts on Gr(1024,28))
  Mean d_proj_norm                     : 0.0169  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 7.3803  (max = 7.4833)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   1 out of  12 | elapsed: 12.7min remaining: 139.9min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 1.012103e-02
  OOS R²                               : -0.2384
  Market-timing Sharpe (annualised)    : 0.100

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.0910  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.0637  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0027  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0257  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 8.2355  (max = 32)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.8702  (expected d_proj for 2 Haar-random pts on Gr(1024,32))
  Mean d_proj_norm                     : 0.0116  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 7.8745  (max = 8.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 1.030118e-02
  OOS R²                               : -0.2604
  Market-timing Sharpe (annualised)    : 0.029

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.0925  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.0647  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0027  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0259  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.9788  (max = 32)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.8702  (expected d_proj for 2 Haar-random pts on Gr(1024,32))
  Mean d_proj_norm                     : 0.0118  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 7.8732  (max = 8.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   3 out of  12 | elapsed: 13.1min remaining: 39.2min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 1.010326e-02
  OOS R²                               : -0.2362
  Market-timing Sharpe (annualised)    : 0.052

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.0938  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.0656  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0027  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0291  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.9667  (max = 32)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.8702  (expected d_proj for 2 Haar-random pts on Gr(1024,32))
  Mean d_proj_norm                     : 0.0119  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 7.8739  (max = 8.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 9.622859e-03
  OOS R²                               : -0.1775
  Market-timing Sharpe (annualised)    : -0.280

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.1223  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.0853  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0042  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0345  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 8.0052  (max = 28)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.3767  (expected d_proj for 2 Haar-random pts on Gr(1024,28))
  Mean d_proj_norm                     : 0.0166  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 7.3803  (max = 7.4833)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   5 out of  12 | elapsed: 22.3min remaining: 31.2min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 9.646675e-03
  OOS R²                               : -0.1804
  Market-timing Sharpe (annualised)    : -0.015

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 0.1257  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 0.0877  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0043  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────���───────────
  Mean |Δd_proj|                       : 0.0355  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 7.9671  (max = 28)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.3767  (expected d_proj for 2 Haar-random pts on Gr(1024,28))
  Mean d_proj_norm                     : 0.0170  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 7.3798  (max = 7.4833)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.401177e-03
  OOS R²                               : -0.0280
  Market-timing Sharpe (annualised)    : 0.351

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3073  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1163  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0558  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0936  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8365  (max = 32)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.8702  (expected d_proj for 2 Haar-random pts on Gr(1024,32))
  Mean d_proj_norm                     : 0.1661  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 6.5455  (max = 8.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   7 out of  12 | elapsed: 103.0min remaining: 73.5min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.407655e-03
  OOS R²                               : -0.0288
  Market-timing Sharpe (annualised)    : 0.304

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3079  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1180  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0558  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0923  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8304  (max = 32)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.8702  (expected d_proj for 2 Haar-random pts on Gr(1024,32))
  Mean d_proj_norm                     : 0.1662  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 6.5518  (max = 8.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.425183e-03
  OOS R²                               : -0.0309
  Market-timing Sharpe (annualised)    : 0.049

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3099  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1182  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0560  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0851  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8327  (max = 32)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.8702  (expected d_proj for 2 Haar-random pts on Gr(1024,32))
  Mean d_proj_norm                     : 0.1664  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 6.5468  (max = 8.0000)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   9 out of  12 | elapsed: 103.2min remaining: 34.4min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.425260e-03
  OOS R²                               : -0.0309
  Market-timing Sharpe (annualised)    : 0.044

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3157  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1208  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0651  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0941  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8344  (max = 28)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.3767  (expected d_proj for 2 Haar-random pts on Gr(1024,28))
  Mean d_proj_norm                     : 0.1784  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.9514  (max = 7.4833)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.400812e-03
  OOS R²                               : -0.0279
  Market-timing Sharpe (annualised)    : 0.359

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3148  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1193  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0648  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0894  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ��───────────────────
  Mean erank                           : 9.8359  (max = 28)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.3767  (expected d_proj for 2 Haar-random pts on Gr(1024,28))
  Mean d_proj_norm                     : 0.1782  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.9454  (max = 7.4833)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.407694e-03
  OOS R²                               : -0.0288
  Market-timing Sharpe (annualised)    : 0.304

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3141  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.1213  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0647  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0920  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8261  (max = 28)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 7.3767  (expected d_proj for 2 Haar-random pts on Gr(1024,28))
  Mean d_proj_norm                     : 0.1781  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.9527  (max = 7.4833)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  12 out of  12 | elapsed: 110.4min finished

                 avg_r2_oos  avg_sharpe  avg_subspace_stability  \
k  P    z
28 1024 z=0e+00   -0.176347   -0.032572                0.124225
        z=1e+01   -0.029199    0.236002                1.314867
32 1024 z=0e+00   -0.245029    0.060255                0.092439
        z=1e+01   -0.029209    0.234576                1.308373

                 avg_max_principal_angle  avg_mean_principal_angle  \
k  P    z
28 1024 z=0e+00                 0.086697                  0.004288
        z=1e+01                 1.120466                  0.064850
32 1024 z=0e+00                 0.064689                  0.002693
        z=1e+01                 1.117502                  0.055888

                 avg_geodesic_accel  avg_erank  avg_erank_collapse  \
k  P    z
28 1024 z=0e+00            0.036144   7.991680                 1.0
        z=1e+01            0.091851   9.832119                 1.0
32 1024 z=0e+00            0.026888   8.060311                 1.0
        z=1e+01            0.090320   9.833184                 1.0

                 avg_spectral_gap
k  P    z
28 1024 z=0e+00               0.0
        z=1e+01               0.0
32 1024 z=0e+00               0.0
        z=1e+01               0.0

#### important  observation -
 While erank is a good measure for a given k, It seems to be increasig with a lot, just from the extra spread we get in higher dimensions even though higher k isnt helping the oos performance of the model perse
 Conclusion? While this maybe a greate measure to compare stability acroros models for a given/fixed k, If we want to compare strategies across k, spetral gap may be a better measure, rate of decrease in spectral gap to be precise?

2. Across k, spectral gap seems to be a reasonable measure of stability, within k erank is good

### run6: adhoc sweep

In [18]:

# ===========================================================================
# 1. (OPTIONAL) OVERRIDE GRID DEFAULTS
#    Uncomment / edit any line to override the defaults from _grass_worker.py
# ===========================================================================
NUM_FACTORS_LIST = [20, 24]     # below k₀, at k₀, above k₀
Z_VALUES         = [50, 100]         # illusory baseline vs virtuous
N_FEATURES_RFF   = [4096]          # P-independence already established
NUM_ITER_RFF     = 3
WINDOW_LEN       = 12
GAMMA            = 0.25
# ===========================================================================
# 2. PREPARE INPUT DATA
#    Dense char matrix for RFF — impute cross-sectionally, then col-wise fallback
# ===========================================================================
date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)        # ensure float64 — required for np.sin/cos in RFF
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [19]:
# ===========================================================================
# 3. RUN PIPELINE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,          # must contain ["Price", "ret"]
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,   # already imported in cell 2
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  3 RFF datasets ready.
Dispatching 12 jobs across 7 workers (cost range 366357–481589, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.378623e-03
  OOS R²                               : -0.0252
  Market-timing Sharpe (annualised)    : 0.466

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3921  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2671  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0930  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0716  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8674  (max = 20)
  erank collapse fraction              : 0.4917  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.3083  (expected d_proj for 2 Haar-random pts on Gr(4096,20))
  Mean d_proj_norm                     : 0.2207  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.2948  (max = 6.3246)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   1 out of  12 | elapsed: 398.8min remaining: 4386.5min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.380865e-03
  OOS R²                               : -0.0255
  Market-timing Sharpe (annualised)    : 0.423

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4098  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4533  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0688  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0173  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8608  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.2041  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.9210  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.377643e-03
  OOS R²                               : -0.0251
  Market-timing Sharpe (annualised)    : 0.471

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4105  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4536  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0691  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0172  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8502  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.2042  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.9227  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   3 out of  12 | elapsed: 404.8min remaining: 1214.5min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.381827e-03
  OOS R²                               : -0.0256
  Market-timing Sharpe (annualised)    : 0.397

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3848  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2736  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0753  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0668  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8752  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.2005  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.1254  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.380521e-03
  OOS R²                               : -0.0254
  Market-timing Sharpe (annualised)    : 0.406

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4102  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4533  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0690  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0170  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8560  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.2042  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.9235  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   5 out of  12 | elapsed: 405.6min remaining: 567.9min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.377909e-03
  OOS R²                               : -0.0251
  Market-timing Sharpe (annualised)    : 0.466

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3838  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2693  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0754  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0664  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8674  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.2003  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.1308  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.381571e-03
  OOS R²                               : -0.0256
  Market-timing Sharpe (annualised)    : 0.424

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3842  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2735  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0752  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0736  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8781  (max = 24)
  erank collapse fraction              : 1.0000  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.9070  (expected d_proj for 2 Haar-random pts on Gr(4096,24))
  Mean d_proj_norm                     : 0.2004  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 5.1237  (max = 6.9282)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   7 out of  12 | elapsed: 405.8min remaining: 289.8min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.381667e-03
  OOS R²                               : -0.0256
  Market-timing Sharpe (annualised)    : 0.423

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3893  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2685  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0927  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0759  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8801  (max = 20)
  erank collapse fraction              : 0.4694  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.3083  (expected d_proj for 2 Haar-random pts on Gr(4096,20))
  Mean d_proj_norm                     : 0.2202  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.3006  (max = 6.3246)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.381740e-03
  OOS R²                               : -0.0256
  Market-timing Sharpe (annualised)    : 0.396

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.3905  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.2684  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0928  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────��───────────
  Mean |Δd_proj|                       : 0.0727  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8760  (max = 20)
  erank collapse fraction              : 0.4861  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.3083  (expected d_proj for 2 Haar-random pts on Gr(4096,20))
  Mean d_proj_norm                     : 0.2204  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.2931  (max = 6.3246)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done   9 out of  12 | elapsed: 597.3min remaining: 199.1min

=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.380950e-03
  OOS R²                               : -0.0255
  Market-timing Sharpe (annualised)    : 0.422

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4126  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4603  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0837  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0203  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ���───────────────────
  Mean erank                           : 9.8623  (max = 20)
  erank collapse fraction              : 0.4806  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.3083  (expected d_proj for 2 Haar-random pts on Gr(4096,20))
  Mean d_proj_norm                     : 0.2239  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.0376  (max = 6.3246)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.377689e-03
  OOS R²                               : -0.0251
  Market-timing Sharpe (annualised)    : 0.471

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4132  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4584  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0840  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0194  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8513  (max = 20)
  erank collapse fraction              : 0.4917  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.3083  (expected d_proj for 2 Haar-random pts on Gr(4096,20))
  Mean d_proj_norm                     : 0.2240  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.0397  (max = 6.3246)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================
=================================================================
  Grassmann-IPCA Backtest Results
=================================================================

── Performance ──────────────────────────────────────────────
  OOS MSE                              : 8.380583e-03
  OOS R²                               : -0.0254
  Market-timing Sharpe (annualised)    : 0.405

── Metric 1 : Projection distance d_proj ────────────────────
  Mean d_proj                          : 1.4130  (lower = more stable)

── Metric 2 : Principal angles (NEW) ────────────────────────
  Mean max angle   (rad)               : 1.4579  (worst-case dir drift; 0 = stable)
  Mean mean angle  (rad)               : 0.0839  (avg dir drift; 0 = stable)

── Metric 3 : Geodesic acceleration (NEW) ───────────────────
  Mean |Δd_proj|                       : 0.0204  (near 0 = converging subspace)

── Metric 4 : Effective rank erank(Σ̂_f) ────────────────────
  Mean erank                           : 9.8571  (max = 20)
  erank collapse fraction              : 0.4889  (fraction of windows erank < k/2)

── Metric 5 : Spectral gap ratio (NEW) ──────────────────────
  Mean gap_ratio                       : 0.0000  (1 = clean signal/noise sep; 0 = last factor on noise floor)

── Metric 6 : Normalised d_proj (NEW) ───────────────────────
  Random baseline                      : 6.3083  (expected d_proj for 2 Haar-random pts on Gr(4096,20))
  Mean d_proj_norm                     : 0.2240  (0=stable, 1=as unstable as random)

── Metric 7 : Between-seed d_proj (NEW) ─────────────────────
  Mean d_proj (warm vs random init)    : 4.0401  (max = 6.3246)
  Flat-Hessian fraction                : 1.0000  (frac windows where seeds landed > 50pct of max apart)
=================================================================

[Parallel(n_jobs=7)]: Done  12 out of  12 | elapsed: 597.8min finished

                 avg_r2_oos  avg_sharpe  avg_subspace_stability  \
k  P    z
20 4096 z=1e+02   -0.025342    0.432275                1.412940
        z=5e+01   -0.025457    0.428213                1.390612
24 4096 z=1e+02   -0.025335    0.433658                1.410176
        z=5e+01   -0.025427    0.428969                1.384300

                 avg_max_principal_angle  avg_mean_principal_angle  \
k  P    z
20 4096 z=1e+02                 1.458871                  0.083848
        z=5e+01                 1.267997                  0.092826
24 4096 z=1e+02                 1.453405                  0.068983
        z=5e+01                 1.272153                  0.075312

                 avg_geodesic_accel  avg_erank  avg_erank_collapse  \
k  P    z
20 4096 z=1e+02            0.020042   9.856880            0.487037
        z=5e+01            0.073419   9.874499            0.482407
24 4096 z=1e+02            0.017149   9.855667            1.000000
        z=5e+01            0.068956   9.873561            1.000000

                 avg_spectral_gap
k  P    z
20 4096 z=1e+02               0.0
        z=5e+01               0.0
24 4096 z=1e+02               0.0
        z=5e+01               0.0

---
## Combined Results — All Longer Backtest Runs (Top-50 Stocks, 1994–2025)

Consolidates Runs 1–6 into a single sheet with `T` (window length) and `run` labels added.  
Derived column `erank_over_k` = erank / k (normalised effective rank, scale-invariant across k).

In [20]:
import pandas as pd, numpy as np

# ── All 30 data points from Runs 1-6, hand-verified from output tables ──
_cols = ["run", "k", "P", "z", "T",
         "avg_r2_oos", "avg_sharpe", "avg_subspace_stability",
         "avg_max_principal_angle", "avg_mean_principal_angle",
         "avg_geodesic_accel", "avg_erank", "avg_erank_collapse",
         "avg_spectral_gap"]

_rows = [
    # ── Run1: k sweep × z={0,10}, P=1024, T=12 ──────────────────────────
    ("Run1",  4, 1024,   0, 12, -0.068738, 0.033662, 0.588709, 0.396841, 0.162658, 0.141023,  3.382539, 0.002778, 2.209187e-01),
    ("Run1",  4, 1024,  10, 12, -0.039922, 0.124149, 1.237812, 0.802710, 0.401132, 0.114294,  3.896735, 0.000000, 5.742925e-01),
    ("Run1",  8, 1024,   0, 12, -0.057367, 0.204040, 0.454414, 0.312912, 0.064608, 0.118081,  5.580585, 0.018519, 4.193812e-02),
    ("Run1",  8, 1024,  10, 12, -0.032434, 0.124780, 1.399760, 0.931821, 0.282069, 0.114831,  7.413556, 0.000926, 3.069561e-01),
    ("Run1", 12, 1024,   0, 12, -0.071727, 0.003268, 0.344688, 0.238305, 0.031907, 0.091721,  6.591813, 0.201852, 1.341996e-03),
    ("Run1", 12, 1024,  10, 12, -0.029523, 0.230358, 1.389662, 1.044526, 0.191994, 0.131073,  9.536090, 0.017593, 4.654315e-02),
    ("Run1", 16, 1024,   0, 12, -0.087863,-0.053282, 0.265426, 0.183657, 0.017896, 0.067055,  7.245099, 0.842593, 9.301977e-20),
    ("Run1", 16, 1024,  10, 12, -0.029346, 0.222280, 1.348005, 1.101556, 0.127026, 0.115175,  9.799155, 0.039815, 2.700167e-19),
    ("Run1", 24, 1024,   0, 12, -0.131690, 0.212184, 0.166530, 0.115938, 0.006965, 0.046309,  7.838482, 1.000000, 0.000000e+00),
    ("Run1", 24, 1024,  10, 12, -0.029227, 0.235614, 1.322483, 1.119238, 0.077522, 0.097656,  9.829161, 1.000000, 0.000000e+00),
    # ── Run2: z sweep at k=12, P=1024, T=24 ─────────────────────────────
    ("Run2", 12, 1024,   1, 24, -0.025695, 0.128234, 0.702229, 0.476902, 0.087819, 0.087755, 10.190136, 0.000000, 0.125995),
    ("Run2", 12, 1024,   5, 24, -0.025263, 0.136353, 1.091539, 0.697246, 0.162069, 0.119769, 11.261268, 0.000000, 0.307757),
    ("Run2", 12, 1024,  20, 24, -0.024232, 0.210213, 1.523093, 0.926063, 0.239712, 0.129528, 11.476672, 0.000000, 0.413193),
    ("Run2", 12, 1024, 100, 24, -0.023507, 0.228131, 1.680029, 1.077929, 0.271522, 0.182214, 11.453914, 0.000000, 0.416803),
    # ── Run3: k sweep at z=20, P=1024, T=24 ─────────────────────────────
    ("Run3",  4, 1024,  20, 24, -0.028626, 0.205029, 1.207916, 0.665261, 0.420080, 0.195350,  3.949825, 0.000000, 0.682406),
    ("Run3",  8, 1024,  20, 24, -0.025686, 0.139891, 1.365448, 0.775875, 0.295348, 0.132879,  7.804608, 0.000000, 0.530543),
    ("Run3", 12, 1024,  20, 24, -0.024179, 0.199393, 1.489824, 0.900135, 0.232489, 0.125496, 11.474806, 0.000000, 0.410738),
    ("Run3", 16, 1024,  20, 24, -0.023297, 0.269948, 1.595065, 1.032811, 0.194694, 0.124586, 14.761079, 0.004789, 0.289968),
    ("Run3", 24, 1024,  20, 24, -0.022573, 0.283874, 1.535360, 1.201785, 0.116767, 0.140719, 18.656600, 0.035441, 0.038902),
    # ── Run4: P sweep at k=24, z=20, T=24 ───────────────────────────────
    ("Run4", 24,   64,  20, 24, -0.034993, 0.029264, 1.419981, 1.438387, 0.083558, 0.033678, 16.232313, 0.068966, 0.027958),
    ("Run4", 24,  256,  20, 24, -0.025566, 0.322742, 1.431380, 1.489980, 0.079834, 0.027295, 18.172800, 0.045019, 0.066218),
    ("Run4", 24, 1024,  20, 24, -0.022553, 0.292026, 1.533880, 1.201230, 0.116747, 0.146800, 18.654884, 0.036398, 0.038813),
    ("Run4", 24, 4096,  20, 24, -0.021038, 0.425746, 1.168918, 0.865519, 0.087508, 0.131056, 17.809959, 0.028736, 0.003130),
    # ── Run5: high-k stress test, P=1024, T=12 ──────────────────────────
    ("Run5", 28, 1024,   0, 12, -0.176347,-0.032572, 0.124225, 0.086697, 0.004288, 0.036144,  7.991680, 1.000000, 0.000000),
    ("Run5", 28, 1024,  10, 12, -0.029199, 0.236002, 1.314867, 1.120466, 0.064850, 0.091851,  9.832119, 1.000000, 0.000000),
    ("Run5", 32, 1024,   0, 12, -0.245029, 0.060255, 0.092439, 0.064689, 0.002693, 0.026888,  8.060311, 1.000000, 0.000000),
    ("Run5", 32, 1024,  10, 12, -0.029209, 0.234576, 1.308373, 1.117502, 0.055888, 0.090320,  9.833184, 1.000000, 0.000000),
    # ── Run6: high-z + high-P, T=12 ─────────────────────────────────────
    ("Run6", 20, 4096,  50, 12, -0.025457, 0.428213, 1.390612, 1.267997, 0.092826, 0.073419,  9.874499, 0.482407, 0.000000),
    ("Run6", 20, 4096, 100, 12, -0.025342, 0.432275, 1.412940, 1.458871, 0.083848, 0.020042,  9.856880, 0.487037, 0.000000),
    ("Run6", 24, 4096,  50, 12, -0.025427, 0.428969, 1.384300, 1.272153, 0.075312, 0.068956,  9.873561, 1.000000, 0.000000),
    ("Run6", 24, 4096, 100, 12, -0.025335, 0.433658, 1.410176, 1.453405, 0.068983, 0.017149,  9.855667, 1.000000, 0.000000),
]

combined = pd.DataFrame(_rows, columns=_cols)

# ── Derived columns ──────────────────────────────────────────────────────
combined["erank_over_k"]   = combined["avg_erank"] / combined["k"]
combined["spectral_gap_pct"] = combined["avg_spectral_gap"] * 100  # easier to read

# ── Sort for readability ─────────────────────────────────────────────────
combined = combined.sort_values(["T", "k", "z", "P"]).reset_index(drop=True)

# ── Save to CSV ──────────────────────────────────────────────────────────
out_path = ROOT_DIR / "notebooks" / "combined_longer_backtest_results.csv"
combined.to_csv(out_path, index=False, float_format="%.6f")
print(f"Saved {len(combined)} rows → {out_path.name}")

# ── Display ──────────────────────────────────────────────────────────────
display_cols = ["run", "k", "P", "z", "T",
                "avg_r2_oos", "avg_sharpe",
                "avg_subspace_stability", "avg_spectral_gap",
                "avg_erank", "erank_over_k", "avg_erank_collapse"]

with pd.option_context("display.max_rows", 40, "display.float_format", "{:.4f}".format):
    display(combined[display_cols])

Saved 31 rows → combined_longer_backtest_results.csv

,run,k,P,z,T,avg_r2_oos,avg_sharpe,avg_subspace_stability,avg_spectral_gap,avg_erank,erank_over_k,avg_erank_collapse
0,Run1,4,1024,0,12,-0.0687,0.0337,0.5887,0.2209,3.3825,0.8456,0.0028
1,Run1,4,1024,10,12,-0.0399,0.1241,1.2378,0.5743,3.8967,0.9742,0.0000
2,Run1,8,1024,0,12,-0.0574,0.2040,0.4544,0.0419,5.5806,0.6976,0.0185
3,Run1,8,1024,10,12,-0.0324,0.1248,1.3998,0.3070,7.4136,0.9267,0.0009
4,Run1,12,1024,0,12,-0.0717,0.0033,0.3447,0.0013,6.5918,0.5493,0.2019
5,Run1,12,1024,10,12,-0.0295,0.2304,1.3897,0.0465,9.5361,0.7947,0.0176
6,Run1,16,1024,0,12,-0.0879,-0.0533,0.2654,0.0000,7.2451,0.4528,0.8426
7,Run1,16,1024,10,12,-0.0293,0.2223,1.3480,0.0000,9.7992,0.6124,0.0398
8,Run6,20,4096,50,12,-0.0255,0.4282,1.3906,0.0000,9.8745,0.4937,0.4824
9,Run6,20,4096,100,12,-0.0253,0.4323,1.4129,0.0000,9.8569,0.4928,0.4870
10,Run1,24,1024,0,12,-0.1317,0.2122,0.1665,0.0000,7.8385,0.3266,1.0000
11,Run1,24,1024,10,12,-0.0292,0.2356,1.3225,0.0000,9.8292,0.4095,1.0000
12,Run6,24,4096,50,12,-0.0254,0.4290,1.3843,0.0000,9.8736,0.4114,1.0000
13,Run6,24,4096,100,12,-0.0253,0.4337,1.4102,0.0000,9.8557,0.4107,1.0000
14,Run5,28,1024,0,12,-0.1763,-0.0326,0.1242,0.0000,7.9917,0.2854,1.0000
15,Run5,28,1024,10,12,-0.0292,0.2360,1.3149,0.0000,9.8321,0.3511,1.0000
16,Run5,32,1024,0,12,-0.2450,0.0603,0.0924,0.0000,8.0603,0.2519,1.0000
17,Run5,32,1024,10,12,-0.0292,0.2346,1.3084,0.0000,9.8332,0.3073,1.0000
18,Run3,4,1024,20,24,-0.0286,0.2050,1.2079,0.6824,3.9498,0.9875,0.0000
19,Run3,8,1024,20,24,-0.0257,0.1399,1.3654,0.5305,7.8046,0.9756,0.0000
20,Run2,12,1024,1,24,-0.0257,0.1282,0.7022,0.1260,10.1901,0.8492,0.0000
21,Run2,12,1024,5,24,-0.0253,0.1364,1.0915,0.3078,11.2613,0.9384,0.0000
22,Run2,12,1024,20,24,-0.0242,0.2102,1.5231,0.4132,11.4767,0.9564,0.0000
23,Run3,12,1024,20,24,-0.0242,0.1994,1.4898,0.4107,11.4748,0.9562,0.0000
24,Run2,12,1024,100,24,-0.0235,0.2281,1.6800,0.4168,11.4539,0.9545,0.0000
25,Run3,16,1024,20,24,-0.0233,0.2699,1.5951,0.2900,14.7611,0.9226,0.0048
26,Run4,24,64,20,24,-0.0350,0.0293,1.4200,0.0280,16.2323,0.6763,0.0690
27,Run4,24,256,20,24,-0.0256,0.3227,1.4314,0.0662,18.1728,0.7572,0.0450
28,Run3,24,1024,20,24,-0.0226,0.2839,1.5354,0.0389,18.6566,0.7774,0.0354
29,Run4,24,1024,20,24,-0.0226,0.2920,1.5339,0.0388,18.6549,0.7773,0.0364
30,Run4,24,4096,20,24,-0.0210,0.4257,1.1689,0.0031,17.8100,0.7421,0.0287

In [21]:
# ── Full combined table (all columns) ────────────────────────────────────
with pd.option_context("display.max_rows", 40, "display.max_columns", 20,
                        "display.float_format", "{:.4f}".format):
    display(combined)

,run,k,P,z,T,avg_r2_oos,avg_sharpe,avg_subspace_stability,avg_max_principal_angle,avg_mean_principal_angle,avg_geodesic_accel,avg_erank,avg_erank_collapse,avg_spectral_gap,erank_over_k,spectral_gap_pct
0,Run1,4,1024,0,12,-0.0687,0.0337,0.5887,0.3968,0.1627,0.1410,3.3825,0.0028,0.2209,0.8456,22.0919
1,Run1,4,1024,10,12,-0.0399,0.1241,1.2378,0.8027,0.4011,0.1143,3.8967,0.0000,0.5743,0.9742,57.4292
2,Run1,8,1024,0,12,-0.0574,0.2040,0.4544,0.3129,0.0646,0.1181,5.5806,0.0185,0.0419,0.6976,4.1938
3,Run1,8,1024,10,12,-0.0324,0.1248,1.3998,0.9318,0.2821,0.1148,7.4136,0.0009,0.3070,0.9267,30.6956
4,Run1,12,1024,0,12,-0.0717,0.0033,0.3447,0.2383,0.0319,0.0917,6.5918,0.2019,0.0013,0.5493,0.1342
5,Run1,12,1024,10,12,-0.0295,0.2304,1.3897,1.0445,0.1920,0.1311,9.5361,0.0176,0.0465,0.7947,4.6543
6,Run1,16,1024,0,12,-0.0879,-0.0533,0.2654,0.1837,0.0179,0.0671,7.2451,0.8426,0.0000,0.4528,0.0000
7,Run1,16,1024,10,12,-0.0293,0.2223,1.3480,1.1016,0.1270,0.1152,9.7992,0.0398,0.0000,0.6124,0.0000
8,Run6,20,4096,50,12,-0.0255,0.4282,1.3906,1.2680,0.0928,0.0734,9.8745,0.4824,0.0000,0.4937,0.0000
9,Run6,20,4096,100,12,-0.0253,0.4323,1.4129,1.4589,0.0838,0.0200,9.8569,0.4870,0.0000,0.4928,0.0000
10,Run1,24,1024,0,12,-0.1317,0.2122,0.1665,0.1159,0.0070,0.0463,7.8385,1.0000,0.0000,0.3266,0.0000
11,Run1,24,1024,10,12,-0.0292,0.2356,1.3225,1.1192,0.0775,0.0977,9.8292,1.0000,0.0000,0.4095,0.0000
12,Run6,24,4096,50,12,-0.0254,0.4290,1.3843,1.2722,0.0753,0.0690,9.8736,1.0000,0.0000,0.4114,0.0000
13,Run6,24,4096,100,12,-0.0253,0.4337,1.4102,1.4534,0.0690,0.0171,9.8557,1.0000,0.0000,0.4107,0.0000
14,Run5,28,1024,0,12,-0.1763,-0.0326,0.1242,0.0867,0.0043,0.0361,7.9917,1.0000,0.0000,0.2854,0.0000
15,Run5,28,1024,10,12,-0.0292,0.2360,1.3149,1.1205,0.0649,0.0919,9.8321,1.0000,0.0000,0.3511,0.0000
16,Run5,32,1024,0,12,-0.2450,0.0603,0.0924,0.0647,0.0027,0.0269,8.0603,1.0000,0.0000,0.2519,0.0000
17,Run5,32,1024,10,12,-0.0292,0.2346,1.3084,1.1175,0.0559,0.0903,9.8332,1.0000,0.0000,0.3073,0.0000
18,Run3,4,1024,20,24,-0.0286,0.2050,1.2079,0.6653,0.4201,0.1953,3.9498,0.0000,0.6824,0.9875,68.2406
19,Run3,8,1024,20,24,-0.0257,0.1399,1.3654,0.7759,0.2953,0.1329,7.8046,0.0000,0.5305,0.9756,53.0543
20,Run2,12,1024,1,24,-0.0257,0.1282,0.7022,0.4769,0.0878,0.0878,10.1901,0.0000,0.1260,0.8492,12.5995
21,Run2,12,1024,5,24,-0.0253,0.1364,1.0915,0.6972,0.1621,0.1198,11.2613,0.0000,0.3078,0.9384,30.7757
22,Run2,12,1024,20,24,-0.0242,0.2102,1.5231,0.9261,0.2397,0.1295,11.4767,0.0000,0.4132,0.9564,41.3193
23,Run3,12,1024,20,24,-0.0242,0.1994,1.4898,0.9001,0.2325,0.1255,11.4748,0.0000,0.4107,0.9562,41.0738
24,Run2,12,1024,100,24,-0.0235,0.2281,1.6800,1.0779,0.2715,0.1822,11.4539,0.0000,0.4168,0.9545,41.6803
25,Run3,16,1024,20,24,-0.0233,0.2699,1.5951,1.0328,0.1947,0.1246,14.7611,0.0048,0.2900,0.9226,28.9968
26,Run4,24,64,20,24,-0.0350,0.0293,1.4200,1.4384,0.0836,0.0337,16.2323,0.0690,0.0280,0.6763,2.7958
27,Run4,24,256,20,24,-0.0256,0.3227,1.4314,1.4900,0.0798,0.0273,18.1728,0.0450,0.0662,0.7572,6.6218
28,Run3,24,1024,20,24,-0.0226,0.2839,1.5354,1.2018,0.1168,0.1407,18.6566,0.0354,0.0389,0.7774,3.8902
29,Run4,24,1024,20,24,-0.0226,0.2920,1.5339,1.2012,0.1167,0.1468,18.6549,0.0364,0.0388,0.7773,3.8813
30,Run4,24,4096,20,24,-0.0210,0.4257,1.1689,0.8655,0.0875,0.1311,17.8100,0.0287,0.0031,0.7421,0.3130

In [22]:
# ── Coverage heatmap: which (k, z) cells exist at each T? ────────────────
print("=" * 60)
print("  COVERAGE MAP — (k, z) cells by window length T")
print("=" * 60)
for t_val in sorted(combined["T"].unique()):
    sub = combined[combined["T"] == t_val]
    pivot = sub.pivot_table(index="k", columns="z", values="avg_sharpe",
                            aggfunc="count", fill_value=0)
    print(f"\n  T = {t_val}  ({len(sub)} cells)")
    print(pivot.to_string())

print("\n" + "=" * 60)
print("  COVERAGE MAP — (k, P) cells by T")
print("=" * 60)
for t_val in sorted(combined["T"].unique()):
    sub = combined[combined["T"] == t_val]
    pivot = sub.pivot_table(index="k", columns="P", values="avg_sharpe",
                            aggfunc="count", fill_value=0)
    print(f"\n  T = {t_val}  ({len(sub)} cells)")
    print(pivot.to_string())

============================================================
  COVERAGE MAP — (k, z) cells by window length T
============================================================

  T = 12  (18 cells)
z   0    10   50   100
k
4     1    1    0    0
8     1    1    0    0
12    1    1    0    0
16    1    1    0    0
20    0    0    1    1
24    1    1    1    1
28    1    1    0    0
32    1    1    0    0

  T = 24  (13 cells)
z   1    5    20   100
k
4     0    0    1    0
8     0    0    1    0
12    1    1    2    1
16    0    0    1    0
24    0    0    5    0

============================================================
  COVERAGE MAP — (k, P) cells by T
============================================================

  T = 12  (18 cells)
P   1024  4096
k
4      2     0
8      2     0
12     2     0
16     2     0
20     0     2
24     2     2
28     2     0
32     2     0

  T = 24  (13 cells)
P   64    256   1024  4096
k
4      0     0     1     0
8      0     0     1     0
12     0     0     5     0
16     0     0     1     0
24     1     1     2     1

### Gap Analysis & Suggested Next Runs

**Current coverage** — 30 cells across 6 runs:

| T | Coverage | What's there |
|---|---------|-------------|
| 12 | 18 cells | k={4–32} × z={0,10} at P=1024; k={20,24} × z={50,100} at P=4096 |
| 24 | 12 cells | k=12 × z={1,5,20,100}; k={4–24} × z=20; k=24 × P={64–4096} |

**Critical gaps:**

1. **z=10 at T=24 is completely missing.** z=10 was the clear sweet spot in the shorter backtest (Sharpe=0.591 at k=8). We have z=10 only at T=12 (Run1). Without T=24 at z=10 we cannot tell whether the z* threshold shifts with window length.

2. **z=0 (illusory baseline) at T=24 is missing.** We cannot compare virtuous vs illusory regimes at T=24 without it.

3. **P variation at T=24** exists only for k=24. No P sweep at lower k values.

---

#### Suggested Run 7 — *highest priority, fills the biggest gap*

```
k = {4, 12, 24},  z = {0, 10},  P = 1024,  T = 24
→  6 jobs
```

**Why:** Directly mirrors Run1 (T=12) at T=24 for three representative k values (low / mid / high). Gives the z=0 vs z=10 comparison at T=24, and enables a clean T=12 vs T=24 panel with all else held fixed. This is the single most informative run.

#### Suggested Run 8 — *second priority, tests P-scaling at the current best configs*

```
k = {12, 16},  z = 20,  P = 4096,  T = 24
→  2 jobs
```

**Why:** Run4 showed P=4096 gives the best Sharpe (0.43) at k=24. But we don't know if that holds at lower k where the spectral gap is healthy. k=12 and k=16 are in the "sweet zone" where sg > 0.25. This tests whether the P-scaling virtue persists when factor structure is genuine.

#### Suggested Run 9 — *optional, completes the z grid at T=24*

```
k = {4, 12, 24},  z = {10, 50},  P = 4096,  T = 24
→  6 jobs
```

**Why:** Tests the "productive illusion" finding (Run6: sg=0 but Sharpe=0.43) at T=24. If the high-z + high-P performance persists at longer windows, it's a real phenomenon, not a short-window artefact.

### Run7 — z={0,10} × k={4,12,24}, P=1024, T=24  *(ready to run)*

In [23]:
# ===========================================================================
# Run7: fills the biggest gap — z=10 at T=24 (+ z=0 baseline)
# ===========================================================================
NUM_FACTORS_LIST = [4, 12, 24]
Z_VALUES         = [0, 10]
N_FEATURES_RFF   = [1024]
NUM_ITER_RFF     = 3
WINDOW_LEN       = 24
GAMMA            = 0.25

date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

X_chars shape : (17803, 74)  (obs × chars)
X_chars dtype : [dtype('float64')]

In [ ]:
# ===========================================================================
# Run7: EXECUTE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)

Pre-computing RFF features ...
  3 RFF datasets ready.
Dispatching 18 jobs across 7 workers (cost range 8192–120397, LPT order) ...

[Parallel(n_jobs=7)]: Using backend LokyBackend with 7 concurrent workers.

### Run8 — k={12,16}, z=20, P=4096, T=24  *(P-scaling at healthy sg)*

In [ ]:
# ===========================================================================
# Run8: P-scaling test where spectral gap is still meaningful
# ===========================================================================
NUM_FACTORS_LIST = [12, 16]
Z_VALUES         = [20]
N_FEATURES_RFF   = [4096]
NUM_ITER_RFF     = 3
WINDOW_LEN       = 24
GAMMA            = 0.25

date_level = "date"
X_chars = df[char_cols].copy()
X_chars = (
    X_chars
    .groupby(level=date_level).transform(lambda s: s.fillna(s.median()))
    .fillna(X_chars.median())
    .fillna(0.0)
    .astype(np.float64)
)
print(f"X_chars shape : {X_chars.shape}  (obs × chars)")
print(f"X_chars dtype : {X_chars.dtypes.unique()}")

In [ ]:
# ===========================================================================
# Run8: EXECUTE
# ===========================================================================
print("Pre-computing RFF features ...")
rff_inputs = build_rff_inputs(
    X_chars               = X_chars,
    df_base               = df,
    n_features_rff        = N_FEATURES_RFF,
    num_iter_rff          = NUM_ITER_RFF,
    gamma                 = GAMMA,
    RandomFourierFeatures = RandomFourierFeatures,
)
print(f"  {len(rff_inputs)} RFF datasets ready.")

jobs = build_jobs(
    rff_inputs       = rff_inputs,
    num_factors_list = NUM_FACTORS_LIST,
    n_features_rff   = N_FEATURES_RFF,
    z_values         = Z_VALUES,
    num_iter_rff     = NUM_ITER_RFF,
    window_len       = WINDOW_LEN,
)

raw_results           = run_sweep(jobs)
results_by_factor_rff = aggregate(raw_results)
results_rff_df        = make_results_df(results_by_factor_rff)
display(results_rff_df)